// publishing-example-projects/angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  showStockFinder = false;
}

<!--The content below is only a placeholder and can be replaced.-->
<jd-stock-price></jd-stock-price>
<jd-stock-finder
  *ngIf="showStockFinder"
></jd-stock-finder>

<button
  *ngIf="!showStockFinder"
  (click)="showStockFinder = true"
>
  Load finder component
</button>

// publishing-example-projects/react.js/src/App.js
import React, { Component } from 'react';
import './App.css';

class App extends Component {
  state = {
    showStockFinder: false
  };

  render() {
    let showStockFinder = <button onClick={() => this.setState({showStockFinder: true})}>Load finder component</button>;
    if (this.state.showStockFinder) {
      showStockFinder = <jd-stock-finder></jd-stock-finder>;
    }
    return (
      <div className="App">
        <jd-stock-price></jd-stock-price>

        {showStockFinder}
      </div>
    );
  }
}

export default App;
